kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: p13
spec:
  jobTemplate:
    spec:
        spec:
          restartPolicy: Never
          dnsPolicy: ClusterFirst
          containers:
            - name: p13-fast-data
              image: domenicoallitude/p13
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 200m
                  memory: 256Mi
              imagePullPolicy: Always