kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: p13
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 3
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: p13
        spec:
          restartPolicy: Never
          dnsPolicy: ClusterFirst
          containers:
            - name: p13-fast-data
              image: domenicoallitude/p13
              env:
                - name: MODALITY
                  value: P13Standard
                - name: URLR
                  valueFrom:
                    secretKeyRef:
                        name: secret-myapp
                        key: URL-SORGENTE
                - name: USERR
                  valueFrom:
                    secretKeyRef:
                        name: secret-myapp
                        key: USERNAME-SORGENTE
                - name: PASSWORDR
                  valueFrom:
                    secretKeyRef:
                        name: secret-myapp
                        key: PASSWORD-SORGENTE
                - name: QUERYR
                  valueFrom:
                    configMapKeyRef:
                        name: config-p13cronjob
                        key: QUERYR
                - name: URLW
                  valueFrom:
                    secretKeyRef:
                        name: secret-myapp
                        key: URL-SORGENTE
                - name: USERW
                  valueFrom:
                    secretKeyRef:
                        name: secret-myapp
                        key: USERNAME-SORGENTE
                - name: PASSWORDW
                  valueFrom:
                    secretKeyRef:
                        name: secret-myapp
                        key: PASSWORD-SORGENTE
                - name: TABLEW
                  valueFrom:
                    configMapKeyRef:
                        name: config-p13cronjob
                        key: TABLEW
                - name: INTERVALROWS
                  valueFrom:
                    configMapKeyRef:
                        name: config-p13cronjob
                        key: INTERVALROWS
                - name: NUMTHREADS
                  valueFrom:
                    configMapKeyRef:
                        name: config-p13cronjob
                        key: NUMTHREADS
                - name: TRUNCATETARGETTABLE
                  valueFrom:
                    configMapKeyRef:
                        name: config-p13cronjob
                        key: TRUNCATETARGETTABLE
                - name: TRUNCATEFUNCTION
                  valueFrom:
                    configMapKeyRef:
                        name: config-p13cronjob
                        key: TRUNCATEFUNCTION
                - name: LOG_LEVEL
                  valueFrom:
                    configMapKeyRef:
                        name: config-p13cronjob
                        key: LOG_LEVEL
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
              imagePullPolicy: Always
status:
  lastScheduleTime: '2020-12-21T13:11:00Z'