apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  template:
    spec:
      containers:
        - name: php-apache
          env:
            - name: ENVIRONMENT
              value: Sviluppo