kind: Secret
apiVersion: v1
metadata:
  namespace: myapp
  name: example-secret
  annotations:
    avp_path: "secret/data/vplugin/supersecret"
type: Opaque
stringData:
  username: <secret:secret/data/vplugin/supersecret~secretkey|base64>
  password: <password>