bases:
    - ../../base
patches:
    - replicacount.yaml
configMapGenerator:
- name: example-config
  namespace: myapp
  files:
  - configs/config.json
patchesStrategicMerge:
    - env.yaml
images:
- name: nginx
  newTag: latest