bases:
    - ../../base
patches:
    - deployments/ngnix/replicas.yaml
    - deployments/ngnix/resources.yaml
    - cronjobs/p13cronjob/resources.yaml
    - cronjobs/p13cronjob/scheduling.yaml
#configMapGenerator:
#- name: example-config
#  namespace: myapp
#  files:
#  - globalconfigmaps/config.json
patchesStrategicMerge:
    - deployments/ngnix/variables.yaml
    - deployments/webserver/variables.yaml
images:
- name: nginx
  newTag: latest
- name: testphp
  newTag: latest
- name: p13
  newTag: latest